/* ‘gD */
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATION_NAME) 
VALUES('1', '‰c‹Æ•”')
GO
INSERT INTO ORGANIZATION (ORGANIZATIONID, ORGANIZATION_NAME) 
VALUES('2', 'Œo—•”')
GO

/* ŽÐˆõ */
INSERT INTO EMPLOYEE (EMPLOYEEID, LOGINID, PASSWORD, EMPLOYEE_NAME, ORGANIZATIONID) 
VALUES('1', 'user01', 'user01', '‘¾˜Y', '1')
GO
INSERT INTO EMPLOYEE (EMPLOYEEID, LOGINID, PASSWORD, EMPLOYEE_NAME, ORGANIZATIONID) 
VALUES('2', 'user02', 'user02', 'ŽŸ˜Y', '1')
GO
INSERT INTO EMPLOYEE (EMPLOYEEID, LOGINID, PASSWORD, EMPLOYEE_NAME, ORGANIZATIONID) 
VALUES('3', 'user03', 'user03', '‰ÔŽq', '2')
GO
INSERT INTO EMPLOYEE (EMPLOYEEID, LOGINID, PASSWORD, EMPLOYEE_NAME, ORGANIZATIONID) 
VALUES('4', 'user04', 'user04', '“Žq', '2')
GO

/* “X•Ü */
INSERT INTO STORE VALUES ('KCD001', 'Ÿ‚Ç‚«–{“X', '“Œ‹ž“s’†‰›‹æŸ‚Ç‚«x')
GO
INSERT INTO STORE VALUES ('OSK001', '‘åã–{’¬“X', '‘åã•{‘åãŽs’†‰›‹æ–{’¬x')
GO
INSERT INTO STORE VALUES ('NGY001', '–¼ŒÃ‰®“X', 'ˆ¤’mŒ§–¼ŒÃ‰®Žs’†‹æ‹Ñx')
GO
INSERT INTO STORE VALUES ('OKZ001', '‰ªè“X', 'ˆ¤’mŒ§‰ªèŽsN¶’Ê“ìx')
GO
INSERT INTO STORE VALUES ('SPR001', '”’Î“X', '–kŠC“¹ŽD–yŽs”’Î‹æx')
GO
INSERT INTO STORE VALUES ('SND001', 'Â—t“X', '‹{éŒ§å‘äŽsÂ—t‹æx')
GO
INSERT INTO STORE VALUES ('NGY002', '‰h“X', '–¼ŒÃ‰®Žs’†‹æ‰hx')
GO
INSERT INTO STORE VALUES ('HRS001', 'L“‡“X', 'L“‡Œ§L“‡Žs’†‹æ‹´–{’¬x')
GO
INSERT INTO STORE VALUES ('FUK001', '•Ÿ‰ª“X', '•Ÿ‰ªŒ§•Ÿ‰ªŽs”Ž‘½‹æx-x')
GO